### ISSUE TITLE
Fails on large Pinboard import

### ISSUE THREAD

**Issue by kerim** [morphinewan/dagonapp.wanyi.dev#2] opened 2020-05-31 07:08 UTC
I have been using Pinboard for years and my database is huge. As a result, the import (initial sync) fails every time I try.

**Comment by morphinewan** [comment] 2020-06-01 00:00
@kerim Sorry for hearing that. Could you please tell me how many bookmarks you stored in Pinboard? I have about more than about 6k records and syncing is good for myself. Please tell me if you have more than this? I'll try my best to solve this issue.

**Comment by morphinewan** [comment] 2020-06-01 00:22
Here is a temporary solution for large pinboard records importing if it failed for some reasons.

1. Export your pinboard bookmarks on its page by visiting [this page](https://pinboard.in/settings/backup). Remember click the [JSON](https://pinboard.in/export/format:json/) format link.
2. If you're using Safari on iOS to export the bookmarks. It will be download and be saved to Files App automatically. If you export them on your computer, please try to transfer the file exported to your iOS device first.
3. Follow the Dagon importing [guide](https://dagonapp.wanyi.dev/#/guide03) , then do the rest operations.

I hope these steps will help you to solve your problem. Best wishes.

**Comment by kerim** [comment] 2020-06-01 01:52
Ha. I was one of the first people to sign up for Pinboard, back before it became a subscription service. I now have 104,044 bookmarks! Probably an edge case so I'm happy to just go with the file import solution you propose. I'll give it a try when I have some time to spare...

**Comment by morphinewan** [comment] 2020-06-01 01:57
Wow, you are an earlier user than me. 100k bookmarks, never thought of that. Blow my mind.

Please keep in touch if you have any problems. Thanks.

**Comment by kerim** [comment] 2020-06-02 00:02
So the iOS app crashes when I try to import the JSON file.

**Comment by morphinewan** [comment] 2020-06-02 00:04
Sorry for that. I will try my best to fix this issue in the next update ASAP. I'll reply this thread when it is done. Please be patient.

**Comment by morphinewan** [comment] 2020-06-05 06:19
@kerim I will push a new test flight version soon. v1.5.0 will fix importing large data failing. If you have any free time, would you please help me to test if your problem is fixed.

Visit url below to be added to Dagon's Testflight group.

https://testflight.apple.com/join/pekxPdD1

Thank you.

**Comment by kerim** [comment] 2020-06-05 07:33
OK. I submitted a crash report through the testflight. (BTW: might it make sense to have the testflight app have a different name so it doesn't replace the current app? I've seen different developers handle this differently, but having a different name seems safer for protecting existing data.)

**Comment by morphinewan** [comment] 2020-06-05 07:50
Thank you for your help. I have downloaded your crash report and it is helpful to me. Let me do some research to fix it.

And you suggest have a different name for app  in test flight. I think it is impossible. Test flight is bonded to the app in store. Even if they have the different names, they have the same bundle ID which caused they share the same sandbox environments. I think Apple set this rule and developers have no idea how to separate the test data and data in production.

**Comment by morphinewan** [comment] 2020-06-05 08:54
Please test with build 28. I think I found the reason and fix it.

**Comment by kerim** [comment] 2020-06-06 02:34
Build 28 is not showing up yet in Testflight. 

Regarding using separate App IDs, I think it might be possible since I’m pretty sure I've seen other developers do this. Looking around on Google I did see some guides like [this one](https://savvyapps.com/blog/using-testflight-to-distribute-multiple-versions-ios-app).

**Comment by morphinewan** [comment] 2020-06-06 02:47
So strange. Would you please send me your account email? I would like to send you a test flight invitation directly.

And thank you for your guides, I will read it later when I have spare time. It will cost a lot of time to setup a new App Bundle and all kinds of service configuration. I should consider the cost of time if it is necessary.

**Comment by kerim** [comment] 2020-06-06 02:54
> And thank you for your guides, I will read it later when I have spare time. It will cost a lot of time to setup a new App Bundle and all kinds of service configuration. I should consider the cost of time if it is necessary.

That is understandable. I've sent you an email with my testflight account contact info.

**Comment by morphinewan** [comment] 2020-06-07 02:28
@kerim I got your test report. Sorry for the bad performance. I’ll try my best to enhance the importing performance.
I will inform you if I have some progress.

**Comment by kerim** [comment] 2020-06-08 10:04
I saw the new version. It fixes the problem. Import was very fast.

(There was a different problem that happened when deleting my old data to test the import - It got hung on deleting the spotlight data. Maybe that should be a new issue, but I would rather not delete my data again to test now that things are working...)

**Comment by morphinewan** [comment] 2020-06-09 00:37
Thank you for your help. I'm glad that your problem was solved. The other issue you mentioned I will deal with it if I can reproduce it later. So I will close this issue now. If you have some other problems, please feel feel to open a new issue here.

**Closed by morphinewan** 2020-06-09 00:37 UTC
Labels: help wanted
